/*
 * Generated by gdbus-codegen 2.47.6. DO NOT EDIT.
 *
 * The license of this code is the same as for the source it was derived from.
 */

#ifndef __ND_FD_NOTIFICATIONS_H__
#define __ND_FD_NOTIFICATIONS_H__

#include <gio/gio.h>

G_BEGIN_DECLS


/* ------------------------------------------------------------------------ */
/* Declarations for org.freedesktop.Notifications */

#define ND_TYPE_FD_NOTIFICATIONS (nd_fd_notifications_get_type ())
#define ND_FD_NOTIFICATIONS(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), ND_TYPE_FD_NOTIFICATIONS, NdFdNotifications))
#define ND_IS_FD_NOTIFICATIONS(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), ND_TYPE_FD_NOTIFICATIONS))
#define ND_FD_NOTIFICATIONS_GET_IFACE(o) (G_TYPE_INSTANCE_GET_INTERFACE ((o), ND_TYPE_FD_NOTIFICATIONS, NdFdNotificationsIface))

struct _NdFdNotifications;
typedef struct _NdFdNotifications NdFdNotifications;
typedef struct _NdFdNotificationsIface NdFdNotificationsIface;

struct _NdFdNotificationsIface
{
  GTypeInterface parent_iface;


  gboolean (*handle_close_notification) (
    NdFdNotifications *object,
    GDBusMethodInvocation *invocation,
    guint arg_id);

  gboolean (*handle_get_capabilities) (
    NdFdNotifications *object,
    GDBusMethodInvocation *invocation);

  gboolean (*handle_get_server_information) (
    NdFdNotifications *object,
    GDBusMethodInvocation *invocation);

  gboolean (*handle_notify) (
    NdFdNotifications *object,
    GDBusMethodInvocation *invocation,
    const gchar *arg_app_name,
    guint arg_replaces_id,
    const gchar *arg_app_icon,
    const gchar *arg_summary,
    const gchar *arg_body,
    const gchar *const *arg_actions,
    GVariant *arg_hints,
    gint arg_expire_timeout);

  void (*action_invoked) (
    NdFdNotifications *object,
    guint arg_id,
    const gchar *arg_action_key);

  void (*notification_closed) (
    NdFdNotifications *object,
    guint arg_id,
    guint arg_reason);

};

GType nd_fd_notifications_get_type (void) G_GNUC_CONST;

GDBusInterfaceInfo *nd_fd_notifications_interface_info (void);
guint nd_fd_notifications_override_properties (GObjectClass *klass, guint property_id_begin);


/* D-Bus method call completion functions: */
void nd_fd_notifications_complete_close_notification (
    NdFdNotifications *object,
    GDBusMethodInvocation *invocation);

void nd_fd_notifications_complete_get_capabilities (
    NdFdNotifications *object,
    GDBusMethodInvocation *invocation,
    const gchar *const *capabilities);

void nd_fd_notifications_complete_get_server_information (
    NdFdNotifications *object,
    GDBusMethodInvocation *invocation,
    const gchar *name,
    const gchar *vendor,
    const gchar *version,
    const gchar *spec_version);

void nd_fd_notifications_complete_notify (
    NdFdNotifications *object,
    GDBusMethodInvocation *invocation,
    guint id);



/* D-Bus signal emissions functions: */
void nd_fd_notifications_emit_action_invoked (
    NdFdNotifications *object,
    guint arg_id,
    const gchar *arg_action_key);

void nd_fd_notifications_emit_notification_closed (
    NdFdNotifications *object,
    guint arg_id,
    guint arg_reason);



/* D-Bus method calls: */
void nd_fd_notifications_call_close_notification (
    NdFdNotifications *proxy,
    guint arg_id,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean nd_fd_notifications_call_close_notification_finish (
    NdFdNotifications *proxy,
    GAsyncResult *res,
    GError **error);

gboolean nd_fd_notifications_call_close_notification_sync (
    NdFdNotifications *proxy,
    guint arg_id,
    GCancellable *cancellable,
    GError **error);

void nd_fd_notifications_call_get_capabilities (
    NdFdNotifications *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean nd_fd_notifications_call_get_capabilities_finish (
    NdFdNotifications *proxy,
    gchar ***out_capabilities,
    GAsyncResult *res,
    GError **error);

gboolean nd_fd_notifications_call_get_capabilities_sync (
    NdFdNotifications *proxy,
    gchar ***out_capabilities,
    GCancellable *cancellable,
    GError **error);

void nd_fd_notifications_call_get_server_information (
    NdFdNotifications *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean nd_fd_notifications_call_get_server_information_finish (
    NdFdNotifications *proxy,
    gchar **out_name,
    gchar **out_vendor,
    gchar **out_version,
    gchar **out_spec_version,
    GAsyncResult *res,
    GError **error);

gboolean nd_fd_notifications_call_get_server_information_sync (
    NdFdNotifications *proxy,
    gchar **out_name,
    gchar **out_vendor,
    gchar **out_version,
    gchar **out_spec_version,
    GCancellable *cancellable,
    GError **error);

void nd_fd_notifications_call_notify (
    NdFdNotifications *proxy,
    const gchar *arg_app_name,
    guint arg_replaces_id,
    const gchar *arg_app_icon,
    const gchar *arg_summary,
    const gchar *arg_body,
    const gchar *const *arg_actions,
    GVariant *arg_hints,
    gint arg_expire_timeout,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean nd_fd_notifications_call_notify_finish (
    NdFdNotifications *proxy,
    guint *out_id,
    GAsyncResult *res,
    GError **error);

gboolean nd_fd_notifications_call_notify_sync (
    NdFdNotifications *proxy,
    const gchar *arg_app_name,
    guint arg_replaces_id,
    const gchar *arg_app_icon,
    const gchar *arg_summary,
    const gchar *arg_body,
    const gchar *const *arg_actions,
    GVariant *arg_hints,
    gint arg_expire_timeout,
    guint *out_id,
    GCancellable *cancellable,
    GError **error);



/* ---- */

#define ND_TYPE_FD_NOTIFICATIONS_PROXY (nd_fd_notifications_proxy_get_type ())
#define ND_FD_NOTIFICATIONS_PROXY(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), ND_TYPE_FD_NOTIFICATIONS_PROXY, NdFdNotificationsProxy))
#define ND_FD_NOTIFICATIONS_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), ND_TYPE_FD_NOTIFICATIONS_PROXY, NdFdNotificationsProxyClass))
#define ND_FD_NOTIFICATIONS_PROXY_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), ND_TYPE_FD_NOTIFICATIONS_PROXY, NdFdNotificationsProxyClass))
#define ND_IS_FD_NOTIFICATIONS_PROXY(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), ND_TYPE_FD_NOTIFICATIONS_PROXY))
#define ND_IS_FD_NOTIFICATIONS_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), ND_TYPE_FD_NOTIFICATIONS_PROXY))

typedef struct _NdFdNotificationsProxy NdFdNotificationsProxy;
typedef struct _NdFdNotificationsProxyClass NdFdNotificationsProxyClass;
typedef struct _NdFdNotificationsProxyPrivate NdFdNotificationsProxyPrivate;

struct _NdFdNotificationsProxy
{
  /*< private >*/
  GDBusProxy parent_instance;
  NdFdNotificationsProxyPrivate *priv;
};

struct _NdFdNotificationsProxyClass
{
  GDBusProxyClass parent_class;
};

GType nd_fd_notifications_proxy_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (NdFdNotificationsProxy, g_object_unref)
#endif

void nd_fd_notifications_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
NdFdNotifications *nd_fd_notifications_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error);
NdFdNotifications *nd_fd_notifications_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);

void nd_fd_notifications_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
NdFdNotifications *nd_fd_notifications_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error);
NdFdNotifications *nd_fd_notifications_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);


/* ---- */

#define ND_TYPE_FD_NOTIFICATIONS_SKELETON (nd_fd_notifications_skeleton_get_type ())
#define ND_FD_NOTIFICATIONS_SKELETON(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), ND_TYPE_FD_NOTIFICATIONS_SKELETON, NdFdNotificationsSkeleton))
#define ND_FD_NOTIFICATIONS_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), ND_TYPE_FD_NOTIFICATIONS_SKELETON, NdFdNotificationsSkeletonClass))
#define ND_FD_NOTIFICATIONS_SKELETON_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), ND_TYPE_FD_NOTIFICATIONS_SKELETON, NdFdNotificationsSkeletonClass))
#define ND_IS_FD_NOTIFICATIONS_SKELETON(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), ND_TYPE_FD_NOTIFICATIONS_SKELETON))
#define ND_IS_FD_NOTIFICATIONS_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), ND_TYPE_FD_NOTIFICATIONS_SKELETON))

typedef struct _NdFdNotificationsSkeleton NdFdNotificationsSkeleton;
typedef struct _NdFdNotificationsSkeletonClass NdFdNotificationsSkeletonClass;
typedef struct _NdFdNotificationsSkeletonPrivate NdFdNotificationsSkeletonPrivate;

struct _NdFdNotificationsSkeleton
{
  /*< private >*/
  GDBusInterfaceSkeleton parent_instance;
  NdFdNotificationsSkeletonPrivate *priv;
};

struct _NdFdNotificationsSkeletonClass
{
  GDBusInterfaceSkeletonClass parent_class;
};

GType nd_fd_notifications_skeleton_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (NdFdNotificationsSkeleton, g_object_unref)
#endif

NdFdNotifications *nd_fd_notifications_skeleton_new (void);


G_END_DECLS

#endif /* __ND_FD_NOTIFICATIONS_H__ */
